### ISSUE TITLE
Should use SecureRandom

### ISSUE THREAD

**Issue by creeper123123321** [UltraBlackLinux/TwoFA#1]
https://github.com/UltraBlackLinux/TwoFA/blob/6d6eb18074dcfcb837a53893c9ffc05a65fc7ecc/src/main/java/me/ultrablacklinux/twofa/util/Account.java#L59
https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html

**Comment by UltraBlackLinux** [comment]
Oh, thank you for that info, I will look into that, even thought I doubt that anyone is going to exploit Java's randomness rather than just reading username and password outta the config.
I also have been thinking about encrypting the passwords with Base, propably gonna push both at once...

The reason, why I used Collections.shuffle is, that I just couldn't figure out, how to get a random number in a specific range... 
Edit: The web scammed me... new Random().nextint(maxrange)

**Comment by UltraBlackLinux** [comment]
https://github.com/UltraBlackLinux/TwoFA/commit/1c342e3551c9fbbe7bcb12507164b329a457d2a2
